.\get-tool.ps1 ls java
.\get-tool.ps1 ls maven
.\get-tool.ps1 ls ant
.\get-tool.ps1 ls gradle
.\get-tool.ps1 ls python
.\get-tool.ps1 ls node
.\get-tool.ps1 ls ruby
.\get-tool.ps1 ls go
.\get-tool.ps1 ls pypy
.\get-tool.ps1 ls cmake
.\get-tool.ps1 ls binaryen
.\get-tool.ps1 ls wasmedge
.\get-tool.ps1 ls wasmer

.\get-tool.ps1 i java
.\get-tool.ps1 i maven
.\get-tool.ps1 i ant
.\get-tool.ps1 i gradle
.\get-tool.ps1 i python
.\get-tool.ps1 i node
.\get-tool.ps1 i ruby
.\get-tool.ps1 i go
.\get-tool.ps1 i pypy
.\get-tool.ps1 i cmake
.\get-tool.ps1 i binaryen
.\get-tool.ps1 i wasmedge
.\get-tool.ps1 i wasmer

.\get-tool.ps1 i java@openjdk
.\get-tool.ps1 i maven@3
.\get-tool.ps1 i ant@1
.\get-tool.ps1 i gradle@7
.\get-tool.ps1 i python@3
.\get-tool.ps1 i node@18
.\get-tool.ps1 i ruby@3
.\get-tool.ps1 i go@1.18
.\get-tool.ps1 i pypy@3.9
.\get-tool.ps1 i cmake@3
.\get-tool.ps1 i binaryen@108
.\get-tool.ps1 i wasmedge@0
.\get-tool.ps1 i wasmer@2
